### ISSUE TITLE
ShmMem is not properly barriered in ForkserverExecutor

### ISSUE THREAD

**Issue by zeyugao** [AFLplusplus/LibAFL#1071]
Use a non-peristent forkserver

This patch will check against the bitmap size for each run. If the bitmap size equals 0, it will wait for user to debug.

```diff
diff --git a/libafl/src/feedbacks/map.rs b/libafl/src/feedbacks/map.rs
index cd0c82745..f9814ae4d 100644
--- a/libafl/src/feedbacks/map.rs
+++ b/libafl/src/feedbacks/map.rs
@@ -11,6 +11,7 @@ use core::{
     marker::PhantomData,
     ops::{BitAnd, BitOr},
 };
+use std::io::{self, BufRead};
 
 use num_traits::PrimInt;
 use serde::{de::DeserializeOwned, Deserialize, Serialize};
@@ -354,7 +355,7 @@ pub struct MapFeedback<N, O, R, S, T> {
 impl<N, O, R, S, T> Feedback<S> for MapFeedback<N, O, R, S, T>
 where
     N: IsNovel<T> + Debug,
-    O: MapObserver<Entry = T> + for<'it> AsIter<'it, Item = T> + Debug,
+    O: MapObserver<Entry = T> + for<'it> AsIter<'it, Item = T> + Debug + AsSlice<Entry = T>,
     R: Reducer<T> + Debug,
     S: UsesInput + HasClientPerfMonitor + HasNamedMetadata + Debug,
     T: Default + Copy + Serialize + for<'de> Deserialize<'de> + PartialEq + Debug + 'static,
@@ -581,7 +582,7 @@ impl<N, O, R, S, T> MapFeedback<N, O, R, S, T>
 where
     T: PartialEq + Default + Copy + 'static + Serialize + DeserializeOwned + Debug,
     R: Reducer<T>,
-    O: MapObserver<Entry = T>,
+    O: MapObserver<Entry = T> + AsSlice<Entry = T>,
     for<'it> O: AsIter<'it, Item = T>,
     N: IsNovel<T>,
     S: UsesInput + HasNamedMetadata + HasClientPerfMonitor + Debug,
@@ -688,7 +689,13 @@ where
 
         let history_map = map_state.history_map.as_mut_slice();
 
+        let mut non_trival_cnt = 0;
+        let initial = observer.initial();
+
         for (i, (item, history)) in observer.as_iter().zip(history_map.iter_mut()).enumerate() {
+            if *item != initial {
+                non_trival_cnt += 1;
+            }
             let reduced = R::reduce(*history, *item);
             if N::is_novel(*history, reduced) {
                 *history = reduced;
@@ -699,6 +706,24 @@ where
             }
         }
 
+        if non_trival_cnt == 0 {
+            let mut non_trival_cnt = 0;
+            for (i, item) in observer.as_iter().enumerate() {
+                if *item != initial {
+                    non_trival_cnt += 1;
+                }
+            }
+
+            println!("observer addr: {:p}", observer.as_slice());
+
+            println!("non_trival_cnt: {}", non_trival_cnt);
+            let stdin = io::stdin();
+            for line in stdin.lock().lines() {
+                println!("{}", line.unwrap());
+            }
+            assert!(false);
+        }
+
         let initial = observer.initial();
         if interesting {
             if let Some(indexes) = self.indexes.as_mut() {
```

I use `forkserver_simple` as trials.

Result:

It will show that the bitmap size of some testcases is 0. But we can check it against with gdb.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/6374697/218775216-84097d9e-f4ff-4c68-b4ae-d65fbc913c92.png">

![image](https://user-images.githubusercontent.com/6374697/218775247-a929299c-9837-44ef-9f52-b77f278c0d08.png)

It seems that it is missing some memory barrier like `#define MEM_BARRIER() __asm__ volatile("" ::: "memory")` in afl

**Comment by tokatoka** [comment]
very nice catch!

**Comment by tokatoka** [comment]
Does #1073 fix this?

**Comment by zeyugao** [comment]
> Does #1073 fix this?

I have tried `compiler_fence` or `fence`, and neither seems to work. If I use stronger re-ordering prevention, like `fence(Ordering::AcqRel)`, It will go further, but it will still get zero bitmap size eventually.

**Comment by tokatoka** [comment]
Is the diff on the first message the only thing necessary to reproduce this?
(I don't have to change the forkserver_simple/src/main.rs ?)

I applied the patch on main, but I can't seem to reproduce this (even on main)

**Comment by tokatoka** [comment]
and I see you get 157 new corpus in the image, that's very strange..
forkserver_simple should only give 3

**Comment by tokatoka** [comment]
Yes I can reproduce this now

**Comment by tokatoka** [comment]
I am seeing that
1.  observer.reset()
2.  harness execution start
3.  harness execution end
4.  maxmapfeedback count 

are happening in this order, but still the observer map is empty 😬

**Comment by tokatoka** [comment]
Okay it seems when the observer is empty the harness is not executed (?)
we get the spawned process pid from the forkserver process, so the communication with the forkserver is successful 
but the target is not executed (why?)


I run it with
```debug_child(true)```
but there's no 
lua output like this sometimes
```
./prog: stdin:327: unfinished long comment (starting at line 48) near <eof>
```

**Comment by zeyugao** [comment]
> I am seeing that
> 
> 1. observer.reset()
> 2. harness execution start
> 3. harness execution end
> 4. maxmapfeedback count
> 
> are happening in this order, but still the observer map is empty 😬

The empty observer map occurs rarely. It might not be related to the incorrect fuzzing logic. But I have no idea why the compiler fence does not solve this.

**Comment by zeyugao** [comment]
> Okay it seems when the observer is empty the harness is not executed (?) we get the spawned process's pid from the forkserver process, so the communication with the forkserver is successful but the target is not executed (why?)
> 
> So probably it's not about race condition or memory barrier
> 
> I run it with `debug_child(true)` but there's no lua output like this sometimes
> 
> ```
> ./prog: stdin:327: unfinished long comment (starting at line 48) near <eof>
> ```

But the gdb check shows that in reality the observer is not empty and if we try to read it again, in the rust layer we can have `non_trival_cnt` > 0.

**Comment by tokatoka** [comment]
> But the gdb check shows that in reality the observer is not empty and if we try to read it again
Yes that's true..

yes, it happens rarely (like probably once in 20 runs?)

The odd thing is,
but, always, in the __2nd__ run of the harness, the observer is empty.
So that's why I think it's not race condition and rather I think I'm missing something in the forkserver implementatin

**Comment by Lukas-Dresel** [comment]
@tokatoka I messaged you on discord with what I think could be the issue

If it's the same problem I've been debugging for the last few days, it's that the forkserver and the client get desynced because the implementation doesn't exactly match. This write_ctl in the implementation in my case is unexpected and gets interpreted as a command to start a first process, thereby desyncing the communication

https://github.com/Lukas-Dresel/LibAFL/blob/2d8984e635b2d97b1c2a09a0d8d0adeed6b36249/libafl/src/executors/forkserver.rs#L775

**Comment by tokatoka** [comment]
@zeyugao 
The latest commit on https://github.com/AFLplusplus/LibAFL/tree/frksrv_fix should fix the bug now

**Comment by domenukk** [comment]
Should be fixed with #1073 and #1076 
Reopen if there are more issues

**Comment by zeyugao** [comment]
I test again and find that it seems that the patch didn't resolve the bug, at least for lua?? I am indeed using the last commit

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/6374697/221630364-56bc6e46-5b2a-477b-adb4-e30706b5de9f.png">

```patch
diff --git a/libafl/src/feedbacks/map.rs b/libafl/src/feedbacks/map.rs
index 7f78ab058..1bd4172d4 100644
--- a/libafl/src/feedbacks/map.rs
+++ b/libafl/src/feedbacks/map.rs
@@ -766,6 +766,8 @@ where
 
         let initial = observer.initial();
 
+        let mut non_trival_cnt = 0;
+
         if let Some(novelties) = self.novelties.as_mut() {
             novelties.clear();
             for (i, item) in observer
@@ -774,6 +776,7 @@ where
                 .enumerate()
                 .filter(|(_, item)| *item != initial)
             {
+                non_trival_cnt += 1;
                 let existing = unsafe { *history_map.get_unchecked(i) };
                 let reduced = R::reduce(existing, item);
                 if N::is_novel(existing, reduced) {
@@ -788,6 +791,7 @@ where
                 .enumerate()
                 .filter(|(_, item)| *item != initial)
             {
+                non_trival_cnt += 1;
                 let existing = unsafe { *history_map.get_unchecked(i) };
                 let reduced = R::reduce(existing, item);
                 if N::is_novel(existing, reduced) {
@@ -797,6 +801,11 @@ where
             }
         }
 
+        assert!(
+            non_trival_cnt > 0,
+            "MapFeedback: no non-trivial items found"
+        );
+
         if interesting || self.always_track {
             let len = history_map.len();
             let filled = history_map.iter().filter(|&&i| i != initial).count();
```

**Comment by tokatoka** [comment]
Equivalent patch as yours
```
        let mut non_trivial = 0;
        if let Some(novelties) = self.novelties.as_mut() {
            novelties.clear();
            for (i, item) in observer
                .as_iter()
                .copied()
                .enumerate()
                .filter(|(_, item)| *item != initial)
            {
                non_trivial += 1;
                let existing = unsafe { *history_map.get_unchecked(i) };
                let reduced = MaxReducer::reduce(existing, item);
                if DifferentIsNovel::is_novel(existing, reduced) {
                    interesting = true;
                    novelties.push(i);
                }
            }
        } else {
            for (i, item) in observer
                .as_iter()
                .copied()
                .enumerate()
                .filter(|(_, item)| *item != initial)
            {
                non_trivial += 1;
                let existing = unsafe { *history_map.get_unchecked(i) };
                let reduced = MaxReducer::reduce(existing, item);
                if DifferentIsNovel::is_novel(existing, reduced) {
                    interesting = true;
                    break;
                }
            }
        }

        if non_trivial == 0 {
            panic!("AAAA");
        }
```

but there's no problem executing it for 3M times

![image](https://user-images.githubusercontent.com/19541930/221665042-cb7e01ed-0046-4f60-a43d-9ee4e108e190.png)

**Comment by zeyugao** [comment]
After some trials, I found that it is because of the lto mode that results in the zero bitmap size.

**Comment by tokatoka** [comment]
ah OK.
you could report that to AFL++

**Comment by tokatoka** [comment]
let me see. then probably related to forkserver autodict.

**Comment by zeyugao** [comment]
If I do some recheck in rust like this:

```rust
        println!("MapFeedback: non-trivial items found: {}", non_trival_cnt);

        if non_trival_cnt == 0 {
            input.to_file("zero_index")?;
            let stdin = io::stdin();
            for line in stdin.lock().lines() {
                println!("{}", line.unwrap());
            }

            for item in observer.as_iter() {
                let value = unsafe { core::ptr::read_volatile(item) };
                if value != initial {
                    non_trival_cnt += 1;
                }
            }

            println!("Read Again: MapFeedback: non-trivial items found: {}", non_trival_cnt);
        }
```

I will get something like this

<img width="454" alt="image" src="https://user-images.githubusercontent.com/6374697/221886169-e344e5bf-c476-4226-ae0a-6a1ccba7aef1.png">

**Comment by tokatoka** [comment]
yes I can reproduce with afl-clang-lto

**Comment by tokatoka** [comment]
again 90% it panics on the 3rd run. must be de-sync

**Comment by tokatoka** [comment]
Should be fixed with #1114
but in my idea, there's a corner case in AFL++ forkserver instrumentation. so I'll ask marc

**Comment by tokatoka** [comment]
Ok. it was my mistake after all.
I think I fixed it in LTO mode too. Can you try #1114 ?

**Comment by zeyugao** [comment]
It works fine now, thanks a lot!!
